<?php

declare(strict_types=1);

namespace Codewithkyrian\Transformers\Pipelines;

use Codewithkyrian\Transformers\Tensor\Tensor;
use Codewithkyrian\Transformers\Utils\Image;

final class TextToAudioPipeline extends Pipeline
{
    private const DEFAULT_VOCODER_ID = 'Xenova/speecht5_hifigan';

    public function __invoke(array|string $inputs, ...$args): array|Image|Tensor
    {
        return parent::__invoke($inputs, $args); // TODO: Change the autogenerated stub
    }

    private function callTextToWaveForm(array|string $inputs): array {}

    private function callTextToSpectrogram(array|string $inputs): array {}
}
